### ISSUE TITLE
Percentage units on width and height

### ISSUE THREAD

**Issue by Yeselimar** [mauricius/vue-draggable-resizable#160] opened 2019-04-18 22:31 UTC
I have my resizable area inside of a parent and it will be nice if this parent were able to set width and height in percentage units, in this way I could use this component in responsive design too.

**Comment by mauricius** [comment] 2019-05-24 15:23
Duplicate of https://github.com/mauricius/vue-draggable-resizable/issues/154

**Closed by mauricius** 2019-05-24 15:23 UTC
