### ISSUE TITLE
Fill parent space on double click

### ISSUE THREAD

**Issue by Romick2005** [mauricius/vue-draggable-resizable#110] opened 2018-09-17 10:51 UTC
Hi, I noticed that fill space on click does't work.
It is from demo https://mauricius.github.io/vue-draggable-resizable
`Bonus: a component constrained in parent, can automatically fill the space just by double-clicking on it.`

**Comment by mauricius** [comment] 2018-09-17 12:43
Thanks for reporting. Actually it's just a missing prop on the demo, not a bug of the component itself.

It has been fixed with fb66967.

Also note that this functionality has been removed from version 2, which is coming out in the near future.

**Closed by mauricius** 2018-09-17 12:43 UTC
