### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by cycold** [mauricius/vue-draggable-resizable#38] opened 2017-10-20 01:24 UTC
Reloading page using shortcut key ('command + r') when the cursor over the draggable element(don't move cursor) then move the  draggable element you can see bellow gif:

![qweqw](https://user-images.githubusercontent.com/2446601/31801089-437b9732-b50b-11e7-8572-2e4cda687cf2.gif)

> sorry, poor English

> That seems handle the first move on the draggable element the `diffX/Y` equals the fisrt `page.x`

**Comment by mauricius** [comment] 2017-10-23 20:24
Wow, nice catch! Don't really know what it's happening there, I'll look into it. Thanks for reporting.

**Comment by Serhiy-Shekhovtsov** [comment] 2017-11-14 21:31
@mauricius I believe the reason is `this.lastMouseX` and `this.lastMouseY` updated on move, but not on mousedown. So if the pointer is already on the draggable element user can press the button and the moving will start but the `this.lastMouseX` and `this.lastMouseY` are both `0` after creating. So when calculating the difference - it will be huge.

**Comment by Serhiy-Shekhovtsov** [comment] 2017-11-14 22:31
Reproduced and fixed locally. Created a pull request.

**Comment by mauricius** [comment] 2017-11-17 20:49
Fixed with 93e4633

**Closed by mauricius** 2017-11-17 20:49 UTC
