### ISSUE TITLE
X and Y properties are not updating properly.

### ISSUE THREAD

**Issue by romucci** [mauricius/vue-draggable-resizable#96] opened 2018-07-03 00:35 UTC
I have 2 lists of Vue draggables which are placed in 2 different components.
They are equal ( one is a map editor for tables in a restaurant and the other one is the actual tables, so they are equal )

Whenever I change the position in the map editor, the actual tables are not updating properly even though the props that hold the position is passed properly to the other component, but apparently X and Y properties are not updating properly, it only works if I re-render the tables by destroying the component.

Any ideas? :D

**Comment by Daedalus11069** [comment] 2018-07-03 01:11
This is a duplicate of #14.

**Closed** 2018-07-03 02:19 UTC
